Repository Team-IT-DA/Frontend, pull requests merged in 2021-08, with the labels that each got.

#26 header 스타일 수정 + 재사용성 추가
  itda-front/src/components/Home/Home.tsx
  itda-front/src/components/Products/Products.tsx
  itda-front/src/components/common/CommonStyles.tsx
  itda-front/src/components/common/Header/Header.tsx
Labels: fix🛠, refactor 🔥

#30 [Feat] login page 뷰 구현 완료
  itda-front/src/components/Login/Login.tsx
  itda-front/src/components/Login/LoginForm.tsx
  itda-front/src/components/Login/LoginStyles.tsx
  itda-front/src/components/common/icons/kakaoLogin.svg
  itda-front/src/components/common/icons/naverLogin.svg
Labels: chore🌷, style🎨

#33 [Feat] brandstory 페이지 구현
  itda-front/src/components/Home/BrandStory.tsx
  itda-front/src/components/Home/Home.tsx
  itda-front/src/components/Home/HomeStyles.tsx
  itda-front/src/components/common/CommonStyles.tsx
  itda-front/src/components/common/Header/Header.tsx
  itda-front/src/styles/GlobalStyles.tsx
Labels: chore🌷, feat✨

#34 [FEAT] search bar, category
  itda-front/src/components/Products/Navigator/CategoryList.tsx
  itda-front/src/components/Products/Navigator/SearchBar.tsx
  itda-front/src/components/Products/Products.tsx
  itda-front/src/components/Products/ProductsStyles.tsx
  itda-front/src/router/Router.tsx
  itda-front/src/types/enums/searchBar.ts
Labels: feat✨

#41 [Feat] Product Detail 페이지 기능 일부 구현
  itda-front/src/components/ProductDetail/ProductDescription.tsx
  itda-front/src/components/ProductDetail/ProductDetail.tsx
  itda-front/src/components/ProductDetail/ProductDetailStyles.ts
  itda-front/src/components/ProductDetail/ProductInfo.tsx
  itda-front/src/components/ProductDetail/ProductReview.tsx
  itda-front/src/components/ProductDetail/ProductTab.tsx
  itda-front/src/router/Router.tsx
  itda-front/src/stores/ProductDetailAtoms.ts
  itda-front/src/types/CommonTypes.ts
  itda-front/src/types/ProductDetailTypes.ts
Labels: chore🌷, feat✨, style🎨

#43 [config] default 브랜치 변경
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/chore.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/fix.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: setting👩‍💻

#40 [FIX] header에 Sidebar 장바구니 붙이기
  itda-front/src/components/ThankYou/ThankYou.tsx
  itda-front/src/components/common/CommonStyles.tsx
  itda-front/src/components/common/Header/Header.tsx
  itda-front/src/components/common/Header/SideDrawer.tsx
Labels: feat✨, fix🛠

#44 [Fix] sidebar 토글 기능 hook 사용방식으로 변경
  itda-front/src/components/common/Header/Header.tsx
Labels: fix🛠

#46 [Feat] Product Detail 페이지 대략적인 기능 로직들 구현 완료
  itda-front/src/components/ProductDetail/ProductDescription.tsx
  itda-front/src/components/ProductDetail/ProductDetailStyles.ts
  itda-front/src/components/ProductDetail/ProductReview.tsx
  itda-front/src/components/ProductDetail/ProductTab.tsx
  itda-front/src/stores/ProductDetailAtoms.ts
  itda-front/src/styles/GlobalStyles.tsx
Labels: feat✨, chore🌷

#47 [Fix] 장바구니 사이드바 스타일 수정 & type 정정
  itda-front/package.json
  itda-front/src/components/common/CommonStyles.tsx
  itda-front/src/components/common/Header/SideDrawer.tsx
  itda-front/yarn.lock
Labels: style🎨, fix🛠

#49 [FIX] src 아래 Router.tsx 파일 삭제 (#48)
  itda-front/src/Router.tsx
Labels: fix🛠

#54 [FEAT] products page view 구현
  itda-front/src/components/Products/Products.tsx
  itda-front/src/components/Products/ProductsStyles.tsx
  itda-front/src/components/common/CommonStyles.tsx
  itda-front/src/components/common/Header/Header.tsx
  itda-front/src/components/common/ProductCard.tsx
  itda-front/src/styles/theme.ts
  itda-front/src/util/throttle.ts
Labels: style🎨, feat✨

#60 [Fix] Product Card 컴포넌트 충돌 해결
  itda-front/src/components/ProductDetail/ProductDetailStyles.ts
  itda-front/src/components/ProductDetail/ProductReview.tsx
  itda-front/src/components/common/CommonStyles.tsx
  itda-front/src/components/common/Header/SideDrawer.tsx
  itda-front/src/components/common/ProductCard.tsx
  itda-front/src/styles/theme.ts
Labels: refactor 🔥, fix🛠

#62 [Feat] 리뷰 포토후기 포토모달 구현(#61)
  itda-front/src/components/ProductDetail/PhotoModal.tsx
  itda-front/src/components/ProductDetail/ProductDetailStyles.ts
  itda-front/src/components/ProductDetail/ProductReview.tsx
Labels: feat✨

#65 [FEAT] Top button 구현, useScrollToggle 추가
  itda-front/src/components/Products/Products.tsx
  itda-front/src/components/common/CommonStyles.tsx
  itda-front/src/components/common/Header/Header.tsx
  itda-front/src/components/common/TopButton.tsx
  itda-front/src/hooks/useScrollToggle.ts
Labels: refactor 🔥, feat✨

#66 Fix/header and side drawer
  itda-front/src/components/Home/Hero.tsx
  itda-front/src/components/Home/Home.tsx
  itda-front/src/components/Home/HomeStyles.tsx
  itda-front/src/components/Login/LoginStyles.tsx
  itda-front/src/components/common/CommonStyles.tsx
  itda-front/src/components/common/Header/Header.tsx
  itda-front/src/components/common/Header/SideDrawer.tsx
  itda-front/src/images/icons/cart.svg
  itda-front/src/images/icons/hamburger.svg
  itda-front/src/images/icons/kakaoLogin.svg
  itda-front/src/images/icons/logo.svg
  itda-front/src/images/icons/naverLogin.svg
  itda-front/src/router/Router.tsx
  itda-front/src/styles/theme.ts
Labels: feat✨, fix🛠

#71 [FIX] header 및 BrandStory 페이지 리팩토링
  itda-front/src/components/BrandStory/BrandStory.tsx
  itda-front/src/components/BrandStory/BrandStoryStyles.tsx
  itda-front/src/components/Home/BrandStory.tsx
  itda-front/src/components/Home/Home.tsx
  itda-front/src/components/Home/HomeStyles.tsx
  itda-front/src/components/Login/Login.tsx
  itda-front/src/components/ProductDetail/ProductDetail.tsx
  itda-front/src/components/Products/Products.tsx
  itda-front/src/components/common/Header/Header.tsx
  itda-front/src/router/Router.tsx
Labels: refactor 🔥, fix🛠

#73 fix: Home & BrandStory 페이지 스타일 수정(#69)
  itda-front/src/components/BrandStory/BrandStoryStyles.tsx
  itda-front/src/components/Home/Hero.tsx
  itda-front/src/components/Home/Home.tsx
  itda-front/src/components/Home/HomeStyles.tsx
Labels: style🎨, fix🛠

#76 [Feat] 리뷰페이지, productDetail 기능 추가 및 수정사항 적용 완료
  itda-front/src/components/ProductDetail/ProductDetail.tsx
  itda-front/src/components/ProductDetail/ProductDetailStyles.ts
  itda-front/src/components/ProductDetail/ProductInfo.tsx
  itda-front/src/components/ProductDetail/ProductReview.tsx
  itda-front/src/components/ProductDetail/mocks.ts
  itda-front/src/components/common/ProductCard.tsx
  itda-front/src/stores/ProductDetailAtoms.ts
  itda-front/src/types/CommonTypes.ts
  itda-front/src/types/ProductDetailTypes.ts
Labels: feat✨, chore🌷

#77 [FEAT] 장바구니 페이지 마크업, 스타일링, 재사용을 위한 Atoms 설계
  itda-front/src/components/ShoppingCart/AddressInfo/AddressFormModal.tsx
  itda-front/src/components/ShoppingCart/AddressInfo/AddressInfo.tsx
  itda-front/src/components/ShoppingCart/AddressInfo/index.ts
  itda-front/src/components/ShoppingCart/PaymentInfo.tsx
  itda-front/src/components/ShoppingCart/ShoppingCart.tsx
  itda-front/src/components/ShoppingCart/ShoppingCartProduct.tsx
  itda-front/src/components/ShoppingCart/ShoppingCartStyles.tsx
  itda-front/src/components/common/Atoms/AtomsStyles.tsx
  itda-front/src/components/common/Atoms/CancelButton.tsx
  itda-front/src/components/common/Atoms/CheckButton.tsx
  itda-front/src/components/common/Atoms/CounterButton.tsx
  itda-front/src/components/common/Atoms/GradientButton.tsx
  itda-front/src/stores/ShoppingCartProductAtoms.ts
Labels: style🎨, feat✨

#82 [Fix] review 페이지 아토믹 버튼 추가 및 match param 설정
  itda-front/src/components/ProductDetail/ProductInfo.tsx
  itda-front/src/router/Router.tsx
Labels: feat✨, fix🛠

#85 [FIX] SideDrawer 닫힐 때 애니메이션 에러 해결 (#84)
  itda-front/src/components/common/CommonStyles.tsx
  itda-front/src/components/common/Header/Header.tsx
  itda-front/src/components/common/Header/SideDrawer.tsx
Labels: refactor 🔥, fix🛠

#90 [FEAT] 회원가입(SignUp) 페이지 UI 구현 (#87)
  itda-front/src/components/SignUp/SignForm.tsx
  itda-front/src/components/SignUp/SignUp.tsx
  itda-front/src/components/SignUp/SignUpStyles.tsx
Labels: style🎨, feat✨

#91 [FEAT] shopping cart페이지의 select 기능 구현
  itda-front/src/components/ProductDetail/ProductInfo.tsx
  itda-front/src/components/ShoppingCart/PaymentInfo.tsx
  itda-front/src/components/ShoppingCart/ShoppingCart.tsx
  itda-front/src/components/ShoppingCart/ShoppingCartProduct.tsx
  itda-front/src/components/ShoppingCart/ShoppingCartService.tsx
  itda-front/src/components/common/Atoms/AtomsStyles.tsx
  itda-front/src/components/common/Atoms/StepperButton.tsx
  itda-front/src/stores/ShoppingCartAtoms.ts
  itda-front/src/stores/ShoppingCartProductAtoms.ts
  itda-front/src/types/ShoppingCartTypes.ts
  itda-front/src/util/mock/GETCartData.ts
  itda-front/tsconfig.json
Labels: feat✨, fix🛠, chore🌷

#96 [Feat] SignupComplete 페이지 뷰 완성
  itda-front/src/components/SignUp/SignUpCompletePage.tsx
  itda-front/src/components/SignUp/SignUpStyles.tsx
  itda-front/src/router/Router.tsx
  itda-front/src/styles/GlobalStyles.tsx
Labels: style🎨

#102 [Fix] AddProduct 최적화
  itda-front/src/components/AddProduct/AddProduct.tsx
  itda-front/src/components/AddProduct/AddProductForm.tsx
  itda-front/src/components/AddProduct/AddProductImageBlock.tsx
  itda-front/src/components/AddProduct/AddProductSelectBox.tsx
  itda-front/src/components/AddProduct/AddProductService.tsx
  itda-front/src/components/AddProduct/AddProductStyles.tsx
  itda-front/src/components/AddProduct/AddProductSubmitLayer.tsx
  itda-front/src/components/AddProduct/AddProductTextField.tsx
  itda-front/src/components/common/TinyEditor.tsx
  itda-front/src/stores/AddProductAtoms.ts
  itda-front/src/types/AddProductTypes.ts
Labels: refactor 🔥

#108 [REFACTOR] Header isSticky prop 추가
  itda-front/src/components/Products/Products.tsx
  itda-front/src/components/common/Header/Header.tsx
Labels: refactor 🔥

#104 [Style] MyReview페이지 뷰 틀 잡기 완료
  itda-front/src/components/MyPage/MyPageStyles.ts
  itda-front/src/components/MyPage/MyReview.tsx
  itda-front/src/router/Router.tsx
Labels: style🎨

#111 [FIX / FEAT] 장바구니 (SideDrawer) 삭제버튼 구현 + 수량 Stepper 버튼 적용
  itda-front/src/components/common/CommonStyles.tsx
  itda-front/src/components/common/Header/SideDrawer.tsx
  itda-front/src/util/mock/GETCartData.ts
Labels: feat✨, fix🛠
