Repository Team-IT-DA/Frontend, pull requests merged in 2021-10, with the labels that each got.

#177 [FEAT] detailPage 쪽 서버 통신 코드 추가 및 데이터 렌더링
  itda-front/src/components/AddProduct/AddProductForm.tsx
  itda-front/src/components/AddProduct/AddProductImageBlock.tsx
  itda-front/src/components/AddProduct/AddProductSelectBox.tsx
  itda-front/src/components/AddProduct/AddProductSelectLayer.tsx
  itda-front/src/components/AddProduct/AddProductStyles.tsx
  itda-front/src/components/ProductDetail/ProductDescription.tsx
  itda-front/src/components/ProductDetail/ProductDetail.tsx
  itda-front/src/components/ProductDetail/ProductDetailSellerBlock.tsx
  itda-front/src/components/ProductDetail/ProductDetailStyles.ts
  itda-front/src/components/ProductDetail/ProductDetailTableBlock.tsx
  itda-front/src/components/ProductDetail/ProductInfo.tsx
  itda-front/src/components/ProductDetail/ProductReview.tsx
  itda-front/src/components/ProductDetail/mocks.ts
  itda-front/src/components/common/Atoms/Pagination.tsx
  itda-front/src/stores/ProductDetailAtoms.ts
  itda-front/src/stores/ProductListAtoms.ts
  itda-front/src/types/ProductDetailTypes.ts
  itda-front/src/util/API/common/interceptors.ts
  itda-front/src/util/API/index.ts
  itda-front/src/util/API/productAPI.ts
Labels: feat✨

#180 [FEAT/FIX] 개인정보수정 페이지 PrivateRoute 적용 + subTab 클릭 시 페이지 전환 로직 적용
  itda-front/src/components/MyPage/MyPage.tsx
  itda-front/src/components/MyPage/MyPageInfo/MyInfoEditAfter.tsx
  itda-front/src/components/MyPage/MyPageInfo/MyInfoEditBefore.tsx
  itda-front/src/components/MyPage/MyPageTab/SellerSubtabs.tsx
  itda-front/src/router/PrivateRouter.tsx
  itda-front/src/router/Router.tsx
  itda-front/src/util/isPasswordCorrect.ts
Labels: refactor 🔥, feat✨

#179 [FEAT] products API 적용
  itda-front/src/components/Products/ProductList.tsx
  itda-front/src/components/Products/Products.tsx
  itda-front/src/components/Products/ProductsService.ts
  itda-front/src/components/Products/ProductsService.tsx
  itda-front/src/components/common/ProductCard.tsx
  itda-front/src/util/API/productAPI.ts
Labels: feat✨

#228 [FEAT] MyPage 기본정보수정 페이지 validation 로직 구현
  itda-front/src/components/MyPage/MyPageInfo/MyInfoEditForm.tsx
  itda-front/src/components/MyPage/MyPageStyles.ts
Labels: feat✨, fix🛠

#230 Refactor/detail api
  itda-front/src/components/ProductDetail/ProductDetail.tsx
  itda-front/src/components/ProductDetail/ProductDetailHeaderBlock.tsx
  itda-front/src/components/ProductDetail/ProductDetailSellerBlock.tsx
  itda-front/src/components/ProductDetail/ProductDetailStyles.ts
  itda-front/src/components/ProductDetail/ProductDetailTableBlock.tsx
  itda-front/src/components/ProductDetail/ProductReview.tsx
  itda-front/src/components/common/TinyEditor.tsx
  itda-front/src/hooks/useReviewList.ts
  itda-front/src/images/defaultPic.jpg
  itda-front/src/stores/ProductDetailAtoms.ts
  itda-front/src/types/ProductDetailTypes.ts
Labels: refactor 🔥, feat✨, fix🛠
