Repository Team-IT-DA/Frontend, pull requests merged in 2021-11, with the labels that each got.

#234 [REFACTOR] Product detail 서비스 코드 분리 및 mail verification
  itda-front/src/components/MyPage/MyPageInfo/MyInfoEditForm.tsx
  itda-front/src/components/ProductDetail/ProductDetail.tsx
  itda-front/src/components/ProductDetail/ProductDetailButtonBlock.tsx
  itda-front/src/components/ProductDetail/ProductDetailCartService.ts
  itda-front/src/components/ProductDetail/ProductDetailService.ts
  itda-front/src/components/ProductDetail/ProductDetailTableBlock.tsx
  itda-front/src/components/ProductDetail/ProductInfo.tsx
  itda-front/src/components/ProductDetail/mocks.ts
  itda-front/src/components/SignUp/SignUpService.ts
  itda-front/src/util/constants.ts
Labels: refactor 🔥, feat✨

#240 [REFACTOR] addProduct 서비스 코드 분리
  itda-front/src/components/AddProduct/AddProduct.tsx
  itda-front/src/components/AddProduct/AddProductImageBlock.tsx
  itda-front/src/components/AddProduct/AddProductService.ts
  itda-front/src/components/AddProduct/AddProductSubmitLayer.tsx
  itda-front/src/components/AddProduct/AddProductTextField.tsx
  itda-front/src/util/API/productAPI.ts
Labels: refactor 🔥, chore🌷

#242 Feat/my page my page info
  itda-front/src/components/MyPage/SellerPage/ProfileImageUploader.tsx
  itda-front/src/components/MyPage/SellerPage/ProfileTextForm.tsx
  itda-front/src/components/MyPage/SellerPage/SellerInfoEdit.tsx
  itda-front/src/components/MyPage/SellerPage/SellerInfoEditService.ts
  itda-front/src/stores/SellerInfoAtoms.ts
  itda-front/src/util/API/sellerAPI.ts
Labels: feat✨

#246 [FEAT] 로그인 구현하기
  itda-front/src/components/Login/LoginForm.tsx
  itda-front/src/components/Login/LoginService.tsx
  itda-front/src/components/SignUp/SignForm.tsx
  itda-front/src/stores/LoginAtoms.ts
  itda-front/src/types/LoginTypes.ts
  itda-front/src/util/API/authAPI.ts
Labels: feat✨

#252 [FEAT] 로그인 로그아웃 상태 처리
  itda-front/src/components/common/Header/Header.tsx
  itda-front/src/components/common/Header/LoginDropDown.tsx
  itda-front/src/stores/LoginAtoms.ts
  itda-front/src/util/API/authAPI.ts
Labels: feat✨
