Repository Team-IT-DA/Frontend, pull requests merged in 2021-07, with the labels that each got.

#13 Feat/product card
  itda-front/src/components/Login/Login.tsx
  itda-front/src/components/common/CommonStyles.tsx
  itda-front/src/components/common/ProductCard.tsx
Labels: feat✨

#17 [feat] header UI 구현
  itda-front/src/components/common/CommonStyles.tsx
  itda-front/src/components/common/Header/Header.tsx
  itda-front/src/components/common/icons/cart.svg
  itda-front/src/components/common/icons/hamburger.svg
  itda-front/src/components/common/icons/logo.svg
Labels: feat✨

#16 [feat] search bar, category list 구현
  itda-front/package-lock.json
  itda-front/package.json
  itda-front/src/components/Products/Navigator/CategoryList.tsx
  itda-front/src/components/Products/Navigator/Navigator.tsx
  itda-front/src/components/Products/Navigator/SearchBar.tsx
  itda-front/src/components/Products/ProductsStyles.tsx
  itda-front/src/hooks/useDebounce.ts
  itda-front/src/hooks/useToggle.ts
  itda-front/src/images/cancel.svg
  itda-front/src/images/hamburger.svg
  itda-front/src/images/search.svg
  itda-front/src/styles/GlobalStyles.tsx
Labels: feat✨

#20 [Feat] home 페이지 UI 작업
  itda-front/src/components/Home/BrandStory.tsx
  itda-front/src/components/Home/Hero.tsx
  itda-front/src/components/Home/Home.tsx
  itda-front/src/components/Home/HomeStyles.tsx
  itda-front/src/images/home_background.jpg
Labels: feat✨, style🎨

#24 [Feat] style 컨벤션대로 수정 및 <StylesProvider injectFirst /> 적용
  itda-front/src/components/common/CommonStyles.tsx
  itda-front/src/components/common/Header/SideDrawer.tsx
  itda-front/src/components/common/ProductCard.tsx
  itda-front/src/index.tsx
Labels: chore🌷, style🎨
