Repository Team-IT-DA/Frontend, pull requests merged in 2021-09, with the labels that each got.

#113 [FIX] 장바구니 합계 계산 로직 구현 & 장바구니 아이템 개별 수량 변경 로직 수정(#112)
  itda-front/src/components/common/CommonStyles.tsx
  itda-front/src/components/common/Header/SideDrawer.tsx
  itda-front/src/stores/CartAtoms.ts
  itda-front/src/types/CartTypes.ts
Labels: refactor 🔥, feat✨, fix🛠

#120 [REFACTOR] product detail페이지 렌더링 최적화
  itda-front/src/components/ProductDetail/ProductDetailButtonBlock.tsx
  itda-front/src/components/ProductDetail/ProductDetailHeaderBlock.tsx
  itda-front/src/components/ProductDetail/ProductDetailSellerBlock.tsx
  itda-front/src/components/ProductDetail/ProductDetailTableBlock.tsx
  itda-front/src/components/ProductDetail/ProductInfo.tsx
  itda-front/src/components/ProductDetail/ProductReview.tsx
  itda-front/src/components/ProductDetail/mocks.ts
  itda-front/src/stores/ProductDetailAtoms.ts
Labels: refactor 🔥

#122 [STYLE] 마이페이지 개인정보 수정 before 창 view 구현완료
  itda-front/src/components/MyPage/MyInfoEditBefore.tsx
  itda-front/src/components/MyPage/MyPage.tsx
  itda-front/src/components/MyPage/MyPageStyles.ts
Labels: style🎨

#121 [STYLE] Thankyou 페이지 뷰 완성
  itda-front/src/components/ThankYou/ThankYou.tsx
  itda-front/src/components/ThankYou/ThankyouStyles.ts
Labels: style🎨

#131 [FEAT] Address Form Modal View 구현
  itda-front/src/components/Cart/AddressForm/AddressForm.tsx
  itda-front/src/components/Cart/AddressForm/AddressFormModal.tsx
  itda-front/src/components/Cart/AddressForm/AddressSelection.tsx
  itda-front/src/components/Cart/AddressForm/DefaultAddressForm.tsx
  itda-front/src/components/Cart/AddressForm/DeliveryRequestForm.tsx
  itda-front/src/components/Cart/AddressForm/LastAddressSelection.tsx
  itda-front/src/components/Cart/AddressForm/NewAddressForm/AddressSearchForm.tsx
  itda-front/src/components/Cart/AddressForm/NewAddressForm/NewAddressForm.tsx
  itda-front/src/components/Cart/AddressForm/NewAddressForm/PhoneNumberForm.tsx
  itda-front/src/components/Cart/AddressForm/NewAddressForm/index.ts
  itda-front/src/components/Cart/AddressForm/index.ts
  itda-front/src/components/Cart/AddressInfo.tsx
  itda-front/src/components/Cart/AddressInfo/AddressFormModal.tsx
  itda-front/src/components/Cart/AddressInfo/index.ts
  itda-front/src/components/Cart/Cart.tsx
  itda-front/src/components/Cart/CartStyles.tsx
  itda-front/src/components/Products/Navigator/SearchBar.tsx
  itda-front/src/components/common/Atoms/AtomsStyles.tsx
  itda-front/src/components/common/Atoms/CancelButton.tsx
  itda-front/src/components/common/Atoms/ConfirmModal.tsx
  itda-front/src/components/common/Atoms/RadioButton.tsx
  itda-front/src/components/common/Atoms/RadioButtonWithCancel.tsx
  itda-front/src/components/common/Atoms/SelectBox.tsx
  itda-front/src/components/common/Atoms/TextInput.tsx
  itda-front/src/styles/theme.ts
  itda-front/src/types/SearchBar.ts
Labels: style🎨, feat✨

#135 [Refactor] 아토믹 컴포넌트 생성
  itda-front/src/components/MyPage/MyInfoEditBefore.tsx
  itda-front/src/components/MyPage/MyPageStyles.ts
  itda-front/src/components/ThankYou/ThankYou.tsx
  itda-front/src/components/ThankYou/ThankyouStyles.ts
  itda-front/src/components/common/Atoms/AtomsStyles.tsx
  itda-front/src/components/common/Atoms/ColorButton.tsx
  itda-front/src/components/common/Atoms/OrderList.tsx
  itda-front/src/util/mock/orderListData.ts
Labels: refactor 🔥

#136 [FEAT] 햄버거 버튼 드롭다운 구현
  itda-front/src/components/common/CommonStyles.tsx
  itda-front/src/components/common/Header/Header.tsx
  itda-front/src/components/common/Header/LoginDropDown.tsx
  itda-front/src/components/common/Header/SideDrawer.tsx
  itda-front/src/stores/LoginAtoms.ts
Labels: style🎨, feat✨

#137 [FEAT/REFACTOR] product page 리팩토링, radio button 토글 로직 구현
  itda-front/src/components/Cart/AddressForm/AddressFormModal.tsx
  itda-front/src/components/Cart/AddressForm/AddressSelection.tsx
  itda-front/src/components/Products/ProductList.tsx
  itda-front/src/components/common/Atoms/RadioButton.tsx
  itda-front/src/components/common/CommonStyles.tsx
  itda-front/src/components/common/ProductCard.tsx
  itda-front/src/hooks/useLazyLoad.ts
  itda-front/src/images/skeletonUI.gif
  itda-front/src/stores/CartAtoms.ts
  itda-front/src/util/mock/productData.ts
Labels: refactor 🔥, feat✨

#130 [FEAT] 개인정보 수정 페이지 View 구현완료
  itda-front/src/components/MyPage/MyInfoEditAfter.tsx
  itda-front/src/components/MyPage/MyPage.tsx
  itda-front/src/components/MyPage/MyPageStyles.ts
  itda-front/src/components/MyPage/MyPageTabs-MU.tsx
  itda-front/src/components/MyPage/MyPageTabs.tsx
Labels: style🎨, feat✨

#140 [FEAT] Orderlist view 띄워두고 Review작성 모달 뷰 + 간단 toggle
  itda-front/src/components/MyPage/MyInfoEditBefore.tsx
  itda-front/src/components/MyPage/MyPageOrderList.tsx
  itda-front/src/components/MyPage/MyPageStyles.ts
  itda-front/src/components/MyPage/ReviewWriteForm.tsx
  itda-front/src/components/common/Atoms/AtomsStyles.tsx
  itda-front/src/components/common/Atoms/ColorButton.tsx
  itda-front/src/components/common/Atoms/OrderList.tsx
Labels: style🎨, feat✨

#147 [REFACTOR] 전반적인 리팩토링 및 에디터 사용법 숙지
  itda-front/src/components/AddProduct/AddProductForm.tsx
  itda-front/src/components/AddProduct/AddProductSelectBox.tsx
  itda-front/src/components/MyPage/MyPageStyles.ts
  itda-front/src/components/ProductDetail/ProductDetailStyles.ts
  itda-front/src/components/ProductDetail/ProductReview.tsx
  itda-front/src/components/common/TinyEditor.tsx
Labels: refactor 🔥, fix🛠, chore🌷

#148 [FEAT] 판매자정보 수정 페이지 구현
  itda-front/src/components/MyPage/MyInfoEditAfter.tsx
  itda-front/src/components/MyPage/MyPage.tsx
  itda-front/src/components/MyPage/MyPageStyles.ts
  itda-front/src/components/MyPage/MyPageTab.tsx
  itda-front/src/components/MyPage/SellerPage/ProfileImageUploader.tsx
  itda-front/src/components/MyPage/SellerPage/ProfileTextForm.tsx
  itda-front/src/components/MyPage/SellerPage/SellerInfoEdit.tsx
  itda-front/src/components/MyPage/SellerPage/SellerInfoStyles.ts
  itda-front/src/components/MyPage/SellerPage/index.ts
  itda-front/src/components/common/Header/Header.tsx
  itda-front/src/stores/SellerInfoAtoms.ts
Labels: feat✨

#150 [FIX] 기본정보수정 페이지 Input 및 Button 수정
  itda-front/src/components/MyPage/MyInfoEditAfter.tsx
  itda-front/src/components/MyPage/MyPage.tsx
  itda-front/src/components/MyPage/MyPageStyles.ts
Labels: fix🛠, chore🌷

#153 [FEAT] OrderList, Cart 기능 구현
  itda-front/src/components/Cart/AddressForm/AddressForm.tsx
  itda-front/src/components/Cart/AddressForm/AddressFormModal.tsx
  itda-front/src/components/Cart/AddressInfo.tsx
  itda-front/src/components/Cart/Cart.tsx
  itda-front/src/components/Cart/CartStyles.tsx
  itda-front/src/components/MyPage/MyPage.tsx
  itda-front/src/components/MyPage/MyPageOrderList.tsx
  itda-front/src/components/MyPage/MyPageOrderList/MyOrderList.tsx
  itda-front/src/components/MyPage/MyPageOrderList/MyPageOrderList.tsx
  itda-front/src/components/MyPage/MyPageOrderList/ReceiptCard.tsx
  itda-front/src/components/MyPage/MyPageOrderList/ReceiptModal.tsx
  itda-front/src/components/MyPage/MyPageOrderList/ReviewWriteForm.tsx
  itda-front/src/components/MyPage/MyPageOrderList/index.ts
  itda-front/src/components/MyPage/MyPageStyles.ts
  itda-front/src/components/common/Atoms/AtomsStyles.tsx
  itda-front/src/types/OrderListTypes.ts
  itda-front/src/util/mock/newOrderListData.ts
Labels: style🎨, feat✨

#152 [FEAT] 판매자용 MyPage 등록상품조회 tab 추가 + 판매자용 subTab 추가
  itda-front/src/components/MyPage/MyPage.tsx
  itda-front/src/components/MyPage/MyPageInfo/MyInfoEditAfter.tsx
  itda-front/src/components/MyPage/MyPageInfo/MyInfoEditBefore.tsx
  itda-front/src/components/MyPage/MyPageOrderList/MyPageOrderList.tsx
  itda-front/src/components/MyPage/MyPageReview/MyReview.tsx
  itda-front/src/components/MyPage/MyPageReview/ReviewWriteForm.tsx
  itda-front/src/components/MyPage/MyPageStyles.ts
  itda-front/src/components/MyPage/MyPageTab.tsx
  itda-front/src/components/MyPage/MyPageTab/MyPageTab.tsx
  itda-front/src/components/MyPage/MyPageTab/MyPageTabs.tsx
  itda-front/src/components/MyPage/MyPageTab/SellerSubtabs.tsx
  itda-front/src/components/MyPage/MyPageTabs.tsx
  itda-front/src/router/Router.tsx
Labels: feat✨

#157 [REFACTOR] 코드 전반적인 리펙토링 + addProduct post로직 구체적으로 정리
  itda-front/src/components/AddProduct/AddProductSubmitLayer.tsx
  itda-front/src/components/ProductDetail/ProductTab.tsx
  itda-front/src/util/apis/common/interceptors.js
  itda-front/src/util/apis/index.js
  itda-front/src/util/apis/seller.js
Labels: refactor 🔥, feat✨

#165 [Refactor] axios 로직 수정 및 addproduct post로직 일부 구현
  itda-front/src/App.tsx
  itda-front/src/components/AddProduct/AddProductSubmitLayer.tsx
  itda-front/src/components/Login/NaverCallback.tsx
  itda-front/src/stores/AddProductAtoms.ts
  itda-front/src/util/API/common/interceptors.js
  itda-front/src/util/API/index.js
  itda-front/src/util/API/myPageAPI.ts
  itda-front/src/util/API/productAPI.ts
Labels: fix🛠

#168 [REFACTOR] MyPage 외 기타 리팩토링
  itda-front/src/components/MyPage/MyPage.tsx
  itda-front/src/components/MyPage/MyPageStyles.ts
  itda-front/src/components/MyPage/MyPageTab/MyPageTab.tsx
  itda-front/src/components/MyPage/MyPageTab/MyPageTabs.tsx
  itda-front/src/components/MyPage/MyPageTab/SellerSubtabs.tsx
  itda-front/src/components/common/Header/LoginDropDown.tsx
  itda-front/src/stores/LoginAtoms.ts
  itda-front/src/stores/MyPageAtoms.ts
Labels: refactor 🔥, fix🛠

#173 [FEAT/REFACTOR] MyPage 서브라우팅 처리하기
  itda-front/src/components/Login/NaverCallback.tsx
  itda-front/src/components/MyPage/MyPage.tsx
  itda-front/src/components/MyPage/MyPageInfo/MyInfoEditAfter.tsx
  itda-front/src/components/MyPage/MyPageInfo/MyInfoEditBefore.tsx
  itda-front/src/components/MyPage/MyPageOrderList/MyPageOrderList.tsx
  itda-front/src/components/MyPage/MyPageReview/MyReview.tsx
  itda-front/src/components/MyPage/MyPageStyles.ts
  itda-front/src/components/MyPage/MyPageTab/MyPageTab.tsx
  itda-front/src/components/MyPage/MyPageTab/MyPageTabs.tsx
  itda-front/src/components/MyPage/MyPageTab/SellerSubtabs.tsx
  itda-front/src/components/MyPage/SellerPage/SellerInfoEdit.tsx
  itda-front/src/components/MyPage/SellerPage/SellerInfoStyles.ts
  itda-front/src/components/ProductDetail/ProductDetail.tsx
  itda-front/src/components/ProductDetail/ProductDetailTableBlock.tsx
  itda-front/src/components/ProductDetail/mocks.ts
  itda-front/src/components/ThankYou/ThankYou.tsx
  itda-front/src/components/common/CommonStyles.tsx
  itda-front/src/components/common/Header/LoginDropDown.tsx
  itda-front/src/stores/AddProductAtoms.ts
  itda-front/src/stores/LoginAtoms.ts
  itda-front/src/stores/MyPageAtoms.ts
  itda-front/src/types/AddProductTypes.ts
  itda-front/src/types/ProductDetailTypes.ts
  itda-front/src/util/API/common/interceptors.js
  itda-front/src/util/API/common/interceptors.ts
  itda-front/src/util/API/index.ts
  itda-front/src/util/API/myPageAPI.ts
  itda-front/src/util/constants.ts
Labels: refactor 🔥, fix🛠
